/* Drop existing table */
DROP TABLE IF EXISTS trade_events;

/* Create enum types */
CREATE TYPE _ACTION AS ENUM ('BUY', 'SELL', 'HOLD');

/* (Re)create tables */

CREATE TABLE trade_events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY,
    chosen_action _ACTION,
    current_price INTEGER,
    last_op_price INTEGER,
    traded_amount INTEGER DEFAULT NULL,
    account_balance INTEGER,
    traded_entity VARCHAR(20),
    broker VARCHAR(20),
    price_enquiry_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    operation_completed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc') NOT NULL,
);

CREATE TABLE error_logs (
    error AS TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc') NOT NULL
);

/* Create indexes */
CREATE INDEX idx_created_at ON trade_events(created_at);
CREATE INDEX idx_trade_action ON trade_events(chosen_action);